name: ⚙️ CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: taiga-family/ci/actions/setup/variables@v1.111.0
      - uses: taiga-family/ci/actions/setup/node@v1.111.0
      - run: npx ng build
      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npx stylelint '**/*.{less,css}' --fix
              npx prettier '**/*.*' --write
              npx eslint . --fix
          else
              npx stylelint '**/*.{less,css}'
              npx prettier '**/*.*' --check
              npx eslint .
          fi
      - uses: taiga-family/ci/actions/auto/push@v1.111.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
